### ISSUE TITLE
tests using `mockAllIsIntersecting` fail after last update

### ISSUE THREAD

**Issue by peterDijk** [onderonur/react-intersection-observer-hook#19]
Hi,
Since last update my tests that use `mockAllIsIntersecting` from `react-intersection-observer/test-utils` are failing. Is there a known issue that connects this failing to the latest update?

**Comment by onderonur** [comment]
Hello there 👋

Unfortunately, I'm not familiar with that package.

I just published a new version to improve observer cache. Previous version had a limitation to use only a single observer on the same element, even if the config parameters were different. Now, it's possible to use multiple observers on the same element as long as their configs are different. Maybe that could be the reason.

Please, try the new version (`v2.1.1`) and update this issue 🙏 

If it works, we can close this issue.
If it does not, I can check it if you provide a minimal reproduction of the issue.

Thanks!

**Comment by peterDijk** [comment]
Hi, thanks for looking into this!
In my component I'm using `react-infinite-scroll-hook` ( I see you also bumped `react-intersection-observer-hook` in there). The component still works fine, also with the latest update. 
In the Jest test I am using the mock function to trigger the `onLoadMore` from the `useInfiniteScroll` hook. 
I realise this mock comes from a different package. 
Is there maybe a different way to trigger the infinitescroll hook in a test ?

**Comment by onderonur** [comment]
Hi there again 👋

I just tried `mockAllIsIntersecting` as below. I tried it on the latest version of `react-infinite-scroll-hook` (`v4.1.1`) and it seems like the test is passing.

It is a very simple test example, but I wanted to share it. Maybe it gives you an idea about the problem in your test, or the reason of why the new version is breaking it.

```tsx
import React from 'react';
import { render } from '@testing-library/react';
import useInfiniteScroll from 'react-infinite-scroll-hook';
import { mockAllIsIntersecting } from 'react-intersection-observer/test-utils';

function Example({ onLoadMore }: { onLoadMore: VoidFunction }) {
  const [sentryRef] = useInfiniteScroll({
    hasNextPage: true,
    loading: false,
    onLoadMore,
  });

  return <div ref={sentryRef}>Foo</div>;
}

beforeEach(() => {
  jest.useFakeTimers();
});

test('calls onLoadMore when intersecting', () => {
  const handleLoadMore = jest.fn();

  const { rerender } = render(<Example onLoadMore={handleLoadMore} />);

  expect(handleLoadMore).not.toBeCalled();

  mockAllIsIntersecting(true);

  rerender(<Example onLoadMore={handleLoadMore} />);

  // Since default delay to run onLoadMore is 100ms.
  jest.advanceTimersByTime(100);

  expect(handleLoadMore).toBeCalledTimes(1);
});
```

**Comment by peterDijk** [comment]
thanks a lot! In my tests I needed to add `setupIntersectionMocking(jest.fn);`
closing this, thanks for looking into it
