### ISSUE TITLE
Intersection observer does not update if config changes

### ISSUE THREAD

**Issue by maerzhase** [onderonur/react-intersection-observer-hook#7]
Hi there! First of all thank you for this very useful lib; I used it a few times now and usually it works as expected. But I had a scenario where i wanted to update the `rootMargin` upon window.resize. Unfortunately the current implementation does not update the observer instance when the config of the observer changes.

Before I suggest a possible solution to this problem I wanted to ask if you are at all interested to solve this problem—or if you maybe took this into consideration already when building the current implementation.

**Comment by onderonur** [comment]
First of all, thanks for the heads up!
It's been a while since this issue was created, but I finally fixed it 🙂.
PR #13 fixes this and I've just published a new major version. 
Also, updated `README.md` based on the new API.

Thanks!

**Comment by maerzhase** [comment]
great job!
